[profile.default]
src = "src"
out = "out"
default = 'optmism-sepolia'
urls = { optimism-goerli = "https://opt-sepolia.g.alchemy.com/v2/_CU3Cf5idymx65yagxV09zT384SeijoH" }
libs = ["node_modules", "lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
